services:
  - type: web
    name: sidequest-backend
    runtime: node
    region: ohio # or frankfurt, oregon, etc.
    plan: free
    repo: https://github.com/oneaurain/Hustle.ai
    rootDir: server # IMPORTANT: Points to your server folder
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false # You will enter this in Render Dashboard for security
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMOB_APP_ID
        sync: false
